version: "2"
services:
    app:
        build: ./app
        command: python main.py run -h 127.0.0.1
        env_file:
            -   '.env'
        links:
            - db
        ports:
            - "40001:40001"

        volumes:
            - .:/code

    db:
        image: mysql:8.0.26
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro/