version: "2"
services:
    app:
        build: ./app
        env_file:
            -   '.env'
        links:
            - db
        ports:
            - "40001:40001"
        environment:
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
            - 'RUN=flask run --host=127.0.0.1 --port=40001'

        command: flask run --host=127.0.0.1 --port=40001

    db:
        image: mysql:8.0.26
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro/